services:
  web:
    build:
     context : ./MachineWebApp
    container_name: machine_app
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - machine_network

  api:
    build: 
     context: ./MachineApi
    container_name: machine_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_CONNECTION=mongodb://machine_mongo:27017
    depends_on:
      - mongo
    networks:
      - machine_network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

    environment:
      - MONGO_CONNECTION=mongodb://machine_mongo:27017

    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: 
    #   MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - mongo_data:/data/db
    networks:
      - machine_network

networks:
  machine_network:
    driver: bridge

volumes:
  mongo_data:
